global:
  runner:
    # use ubuntu VM
    os_image: ubuntu
    # starts redis container in background and exposes the ports
    # locally at localhost:6379
    containers:
      - image: redis

tasks:
  test: ## task name
    steps:
      # Ping test
      - run: (printf "PING\r\n";) | nc localhost 6379
