global:
  runner:
    # use ubuntu VM
    os_image: ubuntu
    # starts redis container in background and exposes the ports
    # locally at localhost:6379
    containers:
      - image: razorci/node

tasks:
  test: ## task name
    steps:
      # Ping test
      - run: git clone https://github.com/Raiyan-Noor/nodejs-demo.git
      - run: cd nodejs-demo
      - run: npm ci
      - run: npm run test
